packages:
  - vendor/*
  - packages/*/*
  - native/landlock-run
  - native/landlock-run/packages/*
  - apps/*
  - examples
  - python/sdk-runtime

linkWorkspacePackages: true

overrides:
  '@deepseek-ai/cosmokit': 'link:vendor/cosmokit'
  '@deepseek-ai/schemastery': 'link:vendor/schemastery'
  'brace-expansion@^5.0.0': 5.0.9
  'protobufjs@^7.0.0': 7.6.5
  'undici@^7.0.0': 7.29.0

peerDependencyRules:
  allowedVersions:
    typescript: '>=5 <7'

allowBuilds:
  esbuild: true
  node-pty: true
  '@google/genai': false
  protobufjs: false
  node-addon-require-builtin: false
  koffi: true
  '@deepseek-ai/dsh-subprocess-local@file:packages/subprocess/subprocess-local': true

minimumReleaseAgeExclude:
  - '@earendil-works/pi-ai@0.82.1'
  - node-addon-native-custom-loader@0.1.4
  - node-addon-require-builtin-darwin-arm64@0.1.4
  - node-addon-require-builtin-darwin-x64@0.1.4
  - node-addon-require-builtin-linux-arm64-gnu@0.1.4
  - node-addon-require-builtin-linux-x64-gnu@0.1.4
  - node-addon-require-builtin-win32-arm64-msvc@0.1.4
  - node-addon-require-builtin-win32-ia32-msvc@0.1.4
  - node-addon-require-builtin-win32-x64-msvc@0.1.4
  - node-addon-require-builtin@0.1.4

patchedDependencies:
  node-pty@1.2.0-beta.15: patches/node-pty@1.2.0-beta.15.patch
