# @generated by tools/generate_schema_types.py. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal, TypeAlias
from uuid import UUID

AIOutputEnvelopeStatus: TypeAlias = Literal['COMPLETED', 'FAILED']

@dataclass(slots=True)
class AIOutputEnvelope:
    run_id: UUID
    provider: str
    status: AIOutputEnvelopeStatus
    artifact_ids: list[UUID]
    payload: Any
    model: str | None = None
    model_version: str | None = None
    raw_confidence: float | None = None
    calibrated_confidence: float | None = None
    provider_metadata: dict[str, Any] | None = None

AIProviderRunStatus: TypeAlias = Literal['CREATED', 'SUBMITTED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED']

@dataclass(slots=True)
class AIProviderRun:
    id: UUID
    capability: str
    provider: str
    endpoint: str
    status: AIProviderRunStatus
    input: Any
    output_artifact_ids: list[UUID]
    created_at: datetime
    updated_at: datetime
    request_id: str | None = None
    status_payload: Any | None = None
    result: Any | None = None
    error: str | None = None
    submitted_at: datetime | None = None
    completed_at: datetime | None = None

@dataclass(slots=True)
class Artifact:
    id: UUID
    content_hash: str
    mime: str
    size_bytes: int
    relative_path: str
    created_at: datetime
    source_url: str | None = None

CanonicalCapabilityRequestCreativityProfile: TypeAlias = Literal['STRICT', 'BALANCED', 'EXPLORATORY', 'DIVERGENT']

@dataclass(slots=True)
class CanonicalCapabilityRequest:
    request_id: UUID
    capability: str
    input_artifact_ids: list[UUID]
    parameters: dict[str, Any]
    creativity_profile: CanonicalCapabilityRequestCreativityProfile
    verification_required: bool
    world_context_ref: str | None = None
    quality_profile: str | None = None
    cost_budget: float | None = None
    latency_budget_ms: int | None = None

@dataclass(slots=True)
class Project:
    id: UUID
    slug: str
    display_name: str
    created_at: datetime
    updated_at: datetime
