/** Generate the runtime-known SessionEventMap vocabulary from source. */
import { globSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, sep } from 'node:path'
import ts from 'typescript'

const root = resolve(import.meta.dirname, '..')
const OUT = 'packages/core/session/src/known-event-types.ts'
const SESSION_PACKAGE = '@deepseek-ai/dsh-session'
const SESSION_TYPES_MODULE = '@deepseek-ai/dsh-session/types'

function packageNameFor(rel: string, scanRoot: string): string | null {
  const dir = rel.split('/').slice(0, 3).join('/')
  try {
    const manifest = JSON.parse(readFileSync(resolve(scanRoot, dir, 'package.json'), 'utf8')) as { name?: string }
    return typeof manifest.name === 'string' ? manifest.name : null
  } catch {
    return null
  }
}

function collectMembers(
  declaration: ts.InterfaceDeclaration,
  sourceFile: ts.SourceFile,
  rel: string,
  seen: Map<string, string>,
): void {
  if (declaration.heritageClauses?.length) {
    throw new Error(`gen-session-event-types: SessionEventMap at ${rel} must declare event keys directly.`)
  }
  for (const member of declaration.members) {
    if (!ts.isPropertySignature(member) || !ts.isStringLiteral(member.name)) {
      throw new Error(`gen-session-event-types: SessionEventMap at ${rel} contains a non-literal property member.`)
    }
    const name = member.name.text
    const line = sourceFile.getLineAndCharacterOfPosition(member.getStart(sourceFile)).line + 1
    const source = `${rel}:${String(line)}`
    const previous = seen.get(name)
    if (previous !== undefined) {
      throw new Error(`gen-session-event-types: duplicate event '${name}' at ${source}; first declared at ${previous}.`)
    }
    seen.set(name, source)
  }
}

/**
 * Collect every repository-owned SessionEventMap key.
 * @param scanRoot - repository root or a fixture root.
 * @returns sorted event type names.
 */
export function collectSessionEventTypes(scanRoot: string = root): string[] {
  const seen = new Map<string, string>()
  let ownerCount = 0
  const files = globSync('packages/*/*/src/**/*.{ts,tsx}', { cwd: scanRoot })
    .map(path => path.split(sep).join('/'))
    .sort()

  for (const rel of files) {
    const text = readFileSync(resolve(scanRoot, rel), 'utf8')
    if (!text.includes('SessionEventMap')) continue
    const sourceFile = ts.createSourceFile(rel, text, ts.ScriptTarget.Latest, true)
    for (const statement of sourceFile.statements) {
      if (ts.isInterfaceDeclaration(statement) && statement.name.text === 'SessionEventMap') {
        if (packageNameFor(rel, scanRoot) !== SESSION_PACKAGE) continue
        const exported = statement.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword) ?? false
        if (!exported) throw new Error(`gen-session-event-types: owning SessionEventMap at ${rel} must be exported.`)
        ownerCount += 1
        if (ownerCount > 1) throw new Error('gen-session-event-types: owning SessionEventMap is declared more than once.')
        collectMembers(statement, sourceFile, rel, seen)
        continue
      }
      if (!ts.isModuleDeclaration(statement)
        || !ts.isStringLiteral(statement.name)
        || statement.name.text !== SESSION_TYPES_MODULE
        || statement.body === undefined
        || !ts.isModuleBlock(statement.body)) continue
      for (const nested of statement.body.statements) {
        if (ts.isInterfaceDeclaration(nested) && nested.name.text === 'SessionEventMap') {
          collectMembers(nested, sourceFile, rel, seen)
        }
      }
    }
  }

  if (ownerCount !== 1) {
    throw new Error(`gen-session-event-types: expected one owning SessionEventMap, found ${String(ownerCount)}.`)
  }
  return [...seen.keys()].sort()
}

/** Render the committed runtime vocabulary module. */
export function renderKnownEventTypes(names: readonly string[]): string {
  return [
    '/**',
    ' * GENERATED by `scripts/gen-session-event-types.ts` — do not edit by hand;',
    ' * run `pnpm run gen-session-event-types` to regenerate.',
    ' * @module @deepseek-ai/dsh-session/known-event-types',
    ' */',
    '',
    '/**',
    ' * Every `SessionEventMap` member declared in this repository — the event',
    ' * vocabulary this build understands. The persistence read path refuses to',
    ' * interpret a log containing a type outside this set unless the event',
    " * carries the envelope's `ignorable` marker (see `SessionEvent.ignorable`",
    ' * in `./types.ts`). Downstream plugin events are outside this list by',
    ' * construction.',
    ' */',
    'export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = new Set([',
    ...[...new Set(names)].sort().map(name => `  '${name}',`),
    '])',
    '',
  ].join('\n')
}

function main(): void {
  const rendered = renderKnownEventTypes(collectSessionEventTypes())
  if (process.argv.includes('--check')) {
    const committed = readFileSync(resolve(root, OUT), 'utf8')
    if (committed !== rendered) {
      console.error('gen-session-event-types: generated runtime vocabulary is stale.')
      process.exitCode = 1
      return
    }
    console.log('gen-session-event-types: runtime vocabulary is up to date.')
    return
  }
  writeFileSync(resolve(root, OUT), rendered)
  console.log(`gen-session-event-types: wrote ${OUT}.`)
}

if (process.argv[1] && import.meta.filename === resolve(process.argv[1])) main()
