// @generated by tools/generate_schema_types.py. DO NOT EDIT.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum AIOutputEnvelopeStatus {
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "FAILED")]
    Failed,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AIOutputEnvelope {
    pub run_id: Uuid,
    pub provider: String,
    pub model: Option<String>,
    pub model_version: Option<String>,
    pub status: AIOutputEnvelopeStatus,
    pub artifact_ids: Vec<Uuid>,
    pub payload: Value,
    pub raw_confidence: Option<f64>,
    pub calibrated_confidence: Option<f64>,
    pub provider_metadata: Option<Value>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum AIProviderRunStatus {
    #[serde(rename = "CREATED")]
    Created,
    #[serde(rename = "SUBMITTED")]
    Submitted,
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "CANCELLED")]
    Cancelled,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AIProviderRun {
    pub id: Uuid,
    pub capability: String,
    pub provider: String,
    pub endpoint: String,
    pub status: AIProviderRunStatus,
    pub request_id: Option<String>,
    pub input: Value,
    pub status_payload: Option<Value>,
    pub result: Option<Value>,
    pub output_artifact_ids: Vec<Uuid>,
    pub error: Option<String>,
    pub submitted_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Artifact {
    pub id: Uuid,
    pub content_hash: String,
    pub mime: String,
    pub size_bytes: u64,
    pub relative_path: String,
    pub source_url: Option<String>,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum CanonicalCapabilityRequestCreativityProfile {
    #[serde(rename = "STRICT")]
    Strict,
    #[serde(rename = "BALANCED")]
    Balanced,
    #[serde(rename = "EXPLORATORY")]
    Exploratory,
    #[serde(rename = "DIVERGENT")]
    Divergent,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CanonicalCapabilityRequest {
    pub request_id: Uuid,
    pub capability: String,
    pub input_artifact_ids: Vec<Uuid>,
    pub world_context_ref: Option<String>,
    pub parameters: Value,
    pub quality_profile: Option<String>,
    pub creativity_profile: CanonicalCapabilityRequestCreativityProfile,
    pub cost_budget: Option<f64>,
    pub latency_budget_ms: Option<u64>,
    pub verification_required: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Project {
    pub id: Uuid,
    pub slug: String,
    pub display_name: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}
