#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PATHS = (
    "apps/desktop/src-tauri",
    "core",
    "compiler",
    "workers/sdk",
    "workers/vision",
    "workers/tools",
    "packages/schema",
    "packages/provider-sdk",
    "packages/plugin-sdk",
    "testdata",
    "tests",
    "tools",
)

REQUIRED_FILES = (
    "apps/desktop/src/coreBridge.ts",
    "apps/desktop/src-tauri/tauri.conf.json",
    "core/src/command_service.rs",
    "core/src/job_engine.rs",
    "core/src/world_repository.rs",
    "compiler/src/lib.rs",
    "workers/sdk/protocol.py",
    "workers/sdk/runtime.py",
    "workers/vision/main.py",
    "workers/tools/main.py",
    "tools/benchmark.py",
)

FORBIDDEN_FILES = {
    "bun.lock",
    "bun.lockb",
    "yarn.lock",
    "package-lock.json",
    "scene.json",
    "project.json",
}

UI_FORBIDDEN = (
    "queue.fal.run",
    "api.worldlabs.ai",
    "fal-ai/",
    "sqlx",
    "rusqlite",
    "better-sqlite3",
)

WORKER_IMPORT_PATTERNS = (
    re.compile(r"^\s*import\s+sqlite3\b", re.MULTILINE),
    re.compile(r"^\s*from\s+sqlite3\b", re.MULTILINE),
    re.compile(r"^\s*import\s+aiosqlite\b", re.MULTILINE),
    re.compile(r"^\s*from\s+sqlalchemy\b", re.MULTILINE),
)

PROVIDER_FORBIDDEN = (
    "world_repository",
    "candidate_service",
    "command_service",
    "UPDATE worlds",
    "INSERT INTO worlds",
    "world_revisions",
)

COMPILER_FORBIDDEN = (
    "sqlx",
    "world_repository",
    "candidate_service",
    "command_service",
    "UPDATE worlds",
    "INSERT INTO worlds",
    "world_revisions",
)

GENERATED_HEADERS = {
    ROOT / "core/src/model/generated.rs": "// @generated by tools/generate_schema_types.py. DO NOT EDIT.",
    ROOT / "apps/desktop/src/generated/schema.ts": "// @generated by tools/generate_schema_types.py. DO NOT EDIT.",
    ROOT / "workers/sdk/generated_models.py": "# @generated by tools/generate_schema_types.py. DO NOT EDIT.",
}


def source_files(root: Path, suffixes: tuple[str, ...]):
    if not root.exists():
        return
    for path in root.rglob("*"):
        if path.is_file() and path.suffix in suffixes:
            yield path


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def main() -> None:
    errors: list[str] = []

    for required in REQUIRED_PATHS:
        if not (ROOT / required).exists():
            errors.append(f"{required}: 缺少项目骨架目录")
    for required in REQUIRED_FILES:
        if not (ROOT / required).is_file():
            errors.append(f"{required}: 缺少项目骨架代码入口")

    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.name in FORBIDDEN_FILES:
            errors.append(f"{relative(path)}: 禁止恢复旧状态文件或第二套包管理器")

    if (ROOT / ".claude").exists():
        errors.append(".claude/: 不允许作为 888 Runtime 重新引入")

    for path in source_files(ROOT / "apps/desktop/src", (".ts", ".tsx")):
        if "/generated/" in f"/{relative(path)}/":
            continue
        text = path.read_text(encoding="utf-8")
        for marker in UI_FORBIDDEN:
            if marker in text:
                errors.append(
                    f"{relative(path)}: UI 不得直接依赖 SQLite 或 Provider 私有 API ({marker})"
                )

    for path in source_files(ROOT / "workers", (".py",)):
        text = path.read_text(encoding="utf-8")
        for pattern in WORKER_IMPORT_PATTERNS:
            if pattern.search(text):
                errors.append(f"{relative(path)}: Worker 不得直接访问正式 SQLite")
        if "core/migrations" in text or "world_revisions" in text:
            errors.append(f"{relative(path)}: Worker 不得直接依赖 Core 持久化结构")

    for path in source_files(ROOT / "core/src/provider", (".rs",)):
        text = path.read_text(encoding="utf-8")
        for marker in PROVIDER_FORBIDDEN:
            if marker in text:
                errors.append(
                    f"{relative(path)}: Provider 不得直接触碰 Canonical World State ({marker})"
                )

    for path in source_files(ROOT / "compiler", (".rs",)):
        text = path.read_text(encoding="utf-8")
        for marker in COMPILER_FORBIDDEN:
            if marker in text:
                errors.append(
                    f"{relative(path)}: Compiler 必须只读 Canonical World State ({marker})"
                )

    for path, header in GENERATED_HEADERS.items():
        if not path.exists():
            errors.append(f"{relative(path)}: 缺少跨语言生成物")
            continue
        first_line = path.read_text(encoding="utf-8").splitlines()[:1]
        if first_line != [header]:
            errors.append(f"{relative(path)}: 生成物头标记丢失，禁止手写第二套协议")

    if errors:
        formatted = "\n".join(f"- {error}" for error in errors)
        raise SystemExit(f"架构边界检查失败：\n{formatted}")

    print("架构边界检查通过")


if __name__ == "__main__":
    main()
