#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_ROOT = ROOT / "packages" / "schema"

OUTPUTS = {
    ROOT / "core" / "src" / "model" / "generated.rs": "rust",
    ROOT / "apps" / "desktop" / "src" / "generated" / "schema.ts": "ts",
    ROOT / "workers" / "sdk" / "generated_models.py": "python",
}


def pascal(value: str) -> str:
    parts = [part for part in re.split(r"[^A-Za-z0-9]+", value) if part]
    return "".join(part[:1].upper() + part[1:] for part in parts)


def enum_name(root: str, prop: str) -> str:
    return root + pascal(prop)


RUST_KEYWORDS = {
    "as", "break", "const", "continue", "crate", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match",
    "mod", "move", "mut", "pub", "ref", "return", "self", "Self", "static",
    "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "abstract", "become", "box", "do",
    "final", "macro", "override", "priv", "typeof", "unsized", "virtual",
    "yield", "try",
}


def rust_field_name(prop: str) -> str:
    return f"r#{prop}" if prop in RUST_KEYWORDS else prop


def type_parts(spec: dict[str, Any]) -> tuple[str | None, bool]:
    value = spec.get("type")
    nullable = False
    if isinstance(value, list):
        nullable = "null" in value
        non_null = [item for item in value if item != "null"]
        value = non_null[0] if non_null else None
    return value, nullable


def enum_variants(values: list[str]) -> list[tuple[str, str]]:
    variants: list[tuple[str, str]] = []
    for raw in values:
        variant = pascal(raw.lower())
        if variant and variant[0].isdigit():
            variant = "Value" + variant
        variants.append((variant, raw))
    return variants


def enum_specs(prop: str, spec: dict[str, Any]):
    if "enum" in spec:
        yield prop, spec
    kind, _ = type_parts(spec)
    if kind == "array":
        yield from enum_specs(prop + "Item", spec.get("items", {}))


def rust_base(spec: dict[str, Any], root: str, prop: str) -> str:
    if "enum" in spec:
        return enum_name(root, prop)
    kind, _ = type_parts(spec)
    if kind == "string":
        if spec.get("format") == "uuid":
            return "Uuid"
        if spec.get("format") == "date-time":
            return "DateTime<Utc>"
        return "String"
    if kind == "integer":
        minimum = spec.get("minimum")
        return "u64" if isinstance(minimum, (int, float)) and minimum >= 0 else "i64"
    if kind == "number":
        return "f64"
    if kind == "boolean":
        return "bool"
    if kind == "array":
        return f"Vec<{rust_base(spec.get('items', {}), root, prop + 'Item')}>"
    return "Value"


def ts_base(spec: dict[str, Any], root: str, prop: str) -> str:
    if "enum" in spec:
        return enum_name(root, prop)
    kind, _ = type_parts(spec)
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return f"Array<{ts_base(spec.get('items', {}), root, prop + 'Item')}>"
    if kind == "object":
        return "Record<string, unknown>"
    return "unknown"


def python_base(spec: dict[str, Any], root: str, prop: str) -> str:
    if "enum" in spec:
        return enum_name(root, prop)
    kind, _ = type_parts(spec)
    if kind == "string":
        if spec.get("format") == "uuid":
            return "UUID"
        if spec.get("format") == "date-time":
            return "datetime"
        return "str"
    if kind == "integer":
        return "int"
    if kind == "number":
        return "float"
    if kind == "boolean":
        return "bool"
    if kind == "array":
        return f"list[{python_base(spec.get('items', {}), root, prop + 'Item')}]"
    if kind == "object":
        return "dict[str, Any]"
    return "Any"


def load_schemas() -> list[dict[str, Any]]:
    schemas: list[dict[str, Any]] = []
    for path in sorted(SCHEMA_ROOT.rglob("*.schema.json")):
        schemas.append(json.loads(path.read_text(encoding="utf-8")))
    if not schemas:
        raise SystemExit("没有找到 Schema")
    return schemas


def render_rust(schemas: list[dict[str, Any]]) -> str:
    lines = [
        "// @generated by tools/generate_schema_types.py. DO NOT EDIT.",
        "",
        "use chrono::{DateTime, Utc};",
        "use serde::{Deserialize, Serialize};",
        "use serde_json::Value;",
        "use uuid::Uuid;",
        "",
    ]
    for schema in schemas:
        title = schema["title"]
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        for prop, spec in props.items():
            for enum_prop, enum_spec in enum_specs(prop, spec):
                name = enum_name(title, enum_prop)
                lines.extend([
                "#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]",
                f"pub enum {name} {{",
            ])
                for variant, raw in enum_variants(enum_spec["enum"]):
                    lines.append(f'    #[serde(rename = "{raw}")]')
                    lines.append(f"    {variant},")
                lines.extend(["}", ""])

        lines.extend([
            "#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]",
            f"pub struct {title} {{",
        ])
        for prop, spec in props.items():
            base = rust_base(spec, title, prop)
            _, nullable = type_parts(spec)
            optional = prop not in required or nullable
            field_type = f"Option<{base}>" if optional else base
            lines.append(f"    pub {rust_field_name(prop)}: {field_type},")
        lines.extend(["}", ""])
    return "\n".join(lines).rstrip() + "\n"


def render_ts(schemas: list[dict[str, Any]]) -> str:
    lines = ["// @generated by tools/generate_schema_types.py. DO NOT EDIT.", ""]
    for schema in schemas:
        title = schema["title"]
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        for prop, spec in props.items():
            for enum_prop, enum_spec in enum_specs(prop, spec):
                values = " | ".join(json.dumps(value) for value in enum_spec["enum"])
                lines.extend([f"export type {enum_name(title, enum_prop)} = {values}", ""])

        lines.append(f"export interface {title} {{")
        for prop, spec in props.items():
            field_type = ts_base(spec, title, prop)
            _, nullable = type_parts(spec)
            if nullable:
                field_type += " | null"
            marker = "" if prop in required else "?"
            lines.append(f"  {prop}{marker}: {field_type}")
        lines.extend(["}", ""])
    return "\n".join(lines).rstrip() + "\n"


def render_python(schemas: list[dict[str, Any]]) -> str:
    lines = [
        "# @generated by tools/generate_schema_types.py. DO NOT EDIT.",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from datetime import datetime",
        "from typing import Any, Literal, TypeAlias",
        "from uuid import UUID",
        "",
    ]
    for schema in schemas:
        title = schema["title"]
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        for prop, spec in props.items():
            for enum_prop, enum_spec in enum_specs(prop, spec):
                values = ", ".join(repr(value) for value in enum_spec["enum"])
                lines.extend([
                    f"{enum_name(title, enum_prop)}: TypeAlias = Literal[{values}]",
                    "",
                ])

        lines.extend(["@dataclass(slots=True)", f"class {title}:"])
        ordered = [
            (prop, spec) for prop, spec in props.items() if prop in required
        ] + [
            (prop, spec) for prop, spec in props.items() if prop not in required
        ]
        for prop, spec in ordered:
            field_type = python_base(spec, title, prop)
            _, nullable = type_parts(spec)
            optional = prop not in required
            if nullable or optional:
                field_type += " | None"
            default = " = None" if optional else ""
            lines.append(f"    {prop}: {field_type}{default}")
        if not ordered:
            lines.append("    pass")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generated_outputs() -> dict[Path, str]:
    schemas = load_schemas()
    renderers = {
        "rust": render_rust,
        "ts": render_ts,
        "python": render_python,
    }
    return {
        path: renderers[language](schemas)
        for path, language in OUTPUTS.items()
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    mismatches: list[Path] = []
    for path, content in generated_outputs().items():
        if args.check:
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content:
                mismatches.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if mismatches:
        formatted = "\n".join(f"- {path}" for path in mismatches)
        raise SystemExit(
            "Schema 生成物已过期，请运行 python tools/generate_schema_types.py：\n"
            + formatted
        )

    print("Schema 三语言生成物一致" if args.check else "Schema 三语言类型已生成")


if __name__ == "__main__":
    main()
